---
title: "<center>Introducción</center>"
subtitle: "<center>Francisca Vilca Sánchez</center>"
autor: ""
date: "<center>`r format(Sys.Date(), '%d/%m/%Y')`</center>"
output: 
    html_document:
        toc: false
        theme:
            bg: 'darkblue'      # Color de fondo
            fg: 'ghostwhite'      # Color fuente y lineas.
            primary: "gold" # Resaltado
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

  El Universo en el que vivimos es inmensamente grande y la comprensión que tenemos de este es practicamente nula, pero gracias al conocimiento cientifico hemos sido capaces de cada día ir avanzando un poco más en entender como funciona este. Para ayudar a que todo este conocimiento que ha sido recolectado llegue a la mayor cantidad de gente posible en este informe intentaremos acercar lo que se sabe acerca de los exoplanetas, los cuales son aquellos planetas que giran alrededor de otra estrella que no es el Sol de nuestro Sistema Solar. Además, para ganar algo de información con este analisis trataremos de identificar aquellos exoplanetas con ciertas características similares a las de nuestro propio planeta. Para ello trabajaremos con una base de datos que contiene a los últimos exoplanetas descubiertos por la humanidad, es decir, entre 1988 y la actualidad.
  
  Se deben estar preguntando porque nos interesaría hablar sobre otros mundos que estan a miles de millones de kilometros de nosotros,y la respuesta es bastante simple, puesto que, a pesar de la distancia entre estos, conocer otros exoplanetas nos será de gran ayuda para tener una mejor comprensión de nuestro propio Sistema Solar y por consiguiente, de La Tierra. Además, a lo largo del último tiempo el cambio climático y el calentamiento global ha ido en aumento, haciendo de nuestro hogar cada día que pasa un lugar menos habitable por los seres vivos. Por ello, las grandes potencias mundiales están comenzando a buscar otras opciones para vivir, por lo que aquí la investigación y búsqueda de los exoplanetas se ha vuelto tan importante.

  Debido a lo anterior, el objetivo de este informe será intentar encontrar aquellos planetas extrasolares con las características más similares a las de la Tierra, utilizando el dataset con la información de los diferentes exoplanetas ya descubiertos hasta el día de hoy.
  
  Este informe se organizará en cuatro secciones, la primera de ellas será la que nos de un contexto sobre que son los exoplanetas, se explicará desde cuando se buscan y la importancia que tienen. La segunda sección será la que exlique la metodología que se usará para hacer el analisis del dataset, para poder extraer la mayor información posible. A continuación, se presentarán los resultados mediante gráficos que resuman la información. Finalmente, se entregan las conclusiones sobre porque es bueno seguir buscando este exoplanetas y porque sería bueno poder llegar a ellos.